packages:
   - 'apps/*'
   - 'blueprint/*'
   - 'modules/*'
   - 'core/*'
   - 'themes/*'
   - 'packages/*'

catalog:
  vue: "latest"
  vue-router: "latest"
  "@nuxt/content": "^2.13.4"
  "@nuxt/fonts": "^0.10.3"
  "@nuxt/image": "^1.9.0"
  "@nuxt/ui-pro": "^1.7.0"
  nuxt: "^3.15.4"
  nuxt-og-image: "^4.1.2"
  "@pinia/nuxt": "^0.9.0"
  pinia: "^2.3.1"
  "@vueuse/core": "^12.5.0"
  "@vueuse/nuxt": "^12.5.0"
  "@vueuse/integrations": "^12.5.0"
  "@nuxt/eslint": "^0.7.5"
  "@nuxthq/studio": "^2.2.1"
  eslint: "^9.19.0"
  vue-tsc: "^2.1.10"
  typescript: "~5.7.3"
  prettier: "^3.4.2"
  valibot: "1.0.0-beta.12"
  vite: "^6.0.7"
  vite-plugin-dts: "^4.5.0"

catalogs:
  resolutions:
    vue-tsc: "2.1.10"
    nuxt: "3.15.2"
    nuxt-og-image: "4.0.3"
    "@pinia/nuxt": "0.9.0"
    pinia: "2.3.1"
